defaults: &defaults
  core:
  backend:
    content_elements:
      content_element: ContentElement
      content_element_html: ContentElementHtml
      content_element_text: ContentElementText
      content_element_image: ContentElementImage
    pages:      
      content_page: ContentPage
      shortcut: ShortcutPage
    languages:
      german: de
      english: en
  frontend:
  website:
    base_url: http://localhost:3000
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults