defaults: &defaults
  core:
  backend:
    pages:      
      content_page:
        icon: "/images/icons/page_green.png"
      shortcut:
        icon: "/images/icons/page_green.png"
      external_url:
        icon: "/images/icons/page_green.png"
    languages:
      german: de
      english: en
  frontend:
  website:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults