defaults: &defaults
  core:
  backend:
    pages:
      content_page:
        icon: "/images/icons/page_green.png"
      shortcut:
        icon: ""
      external_url:
        icon: ""
    languages:
      de: german
      en: english
  frontend:
  website:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults