defaults: &defaults
  core:
  backend:
    pages:      
      content_page: ContentPage
      shortcut: ShortcutPage
    languages:
      german: de
      english: en
  frontend:
  website:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults